# Generated by Django 3.2.16 on 2023-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_label_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
