# Generated by Django 3.2.16 on 2023-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_label_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='labels',
            field=models.TextField(default=''),
        ),
    ]
